version: '3.7'

services:
    notejam:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        command: ./manage.py runserver 0.0.0.0:8000
        ports:
        - 8000:8000
