#=============================#
#     Docker compose.yaml     #
#=============================#
#    Created by: Marc Bayón   #
#                             #
#=============================#

version: '3.7'

services:
    notejam:
        build:
            context: ./notejam-container
            dockerfile: Dockerfile
        tty: true
        env_file: 
            - ./notejam-container/.env
        command: /bin/bash -c "env && /notejam/init.sh"
        networks:
            - my-network
        ports:
        - 8000:8000

    nginx:
        build: ./nginx-container
        ports:
            - 80:80
            - 443:443
        networks:
            - my-network
        depends_on:
            - notejam
networks:
    my-network:
        driver: bridge
