#=============================#
#          K8s.yaml           #
#=============================#
#    Created by: Marc Bayón   #
#                             #
#=============================#


# 1) K8s Namespace:
# Create Namespaces for dev + qa & prod

apiVersion: v1
kind: Namespace
metadata:
  name: notejam
  labels: 
    name: notejam
---

# 2) 
# Global ConfigMap for all the pods

apiVersion: v1
kind: ConfigMap
data:
  DATABASE_URL: ""
metadata:
  creationTimestamp: null
  labels:
    app: all
  name: global-configmap
  namespace: nootejam  
---
# 3) 
#=================================
#----------->NOTEJAM<------------#
#=================================
# ConfigMap for notejam

# 5) Deployment- Notejam
# Pull the container from registry
# Open Port 8000
# Mount the PV inside on path /home/ciberseguro/web/staticfiles
# Configure DB connection reading from the ConfigMap

apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: notejam
  name: notejam-deployment
  namespace: notejam
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: notejam
  strategy: 
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: notejam
    spec:
      restartPolicy: Always
      containers:
      - name: notejam
        image: ".azurecr.io/notejam:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        lifecycle:
          postStart:
            exec:
              command: ["cp", "-r","-f", "web/static/.","staticfiles/" ]
        args: 
        - "python"
        - "manage.py"
        - "runserver"
        - "0.0.0.0:8000"
        env: 
          - name: DEBUG
            valueFrom: 
              configMapKeyRef: 
                key: DEBUG
                name: global-configmap


---
#4) Service - Notetam
# Expose port 8000 pod to the internal cluster network

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: notejam
  name: notejam
  namespace: notejam
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    app: notejam
status:
  loadBalancer: {}

---

#=================================
#------------>NGNIX<-------------#
#=================================

# 13) Deployment - NGINX
# Pull Image from registry
# Read config on persistance volume dumped by loki (TODO in dockerfile)
# Open Port 80

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: notejam
  annotations:
    app: nginx
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: dooingit.azurecr.io/nginx:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /home/ciberseguro/web/staticfiles
          name: tempu-prod-claim0
      restartPolicy: Always
      volumes:
      - name: tempu-prod-claim0
        persistentVolumeClaim:
          claimName: tempu-prod-claim0
---
# 14) Service - NGINX
# Expose port 80 of NGINX pod to the internal cluster network

apiVersion: v1
kind: Service
metadata:
 creationTimestamp: null
 labels:
   app: nginx
 name: nginx-tempu-service-lb
 namespace: tempu-prod
spec:
 ports:
 - name: "http"
   port: 80
   targetPort: 80
 - name: https
   port: 443
   targetPort: 443
 selector:
   app: nginx
 type: LoadBalancer
---