#####################################
#   Task: 1)Install Namespaces      #
#        Role: cluster config       #
#####################################
#                                   #
#        Author:Marc Bayon          #
#####################################

- name: (Cluster Configuration) Verify the platform namespace exits
  shell: kubectl get namespace {{namespace}}
  ignore_errors: yes
  register: namespace_platf_result
  tags: namespaces

- set_fact:
    exitsPlatfns: "{{namespace_platf_result.stdout_lines}}"
  tags: namespaces

- name: (Cluster Configuration) Create ingress namespace
  shell: kubectl create namespace {{namespace}}
  when: exitsPlatfns|length == 0
  tags: namespaces