#####################################
#   Task: 2)K8s_components          #
#        Role: cluster config       #
#####################################
#                                   #
#       Author:Marc Bayón           #
#####################################


- name: (Cluster Configuration) Get Public IP generated in Azure role.
  azure_rm_publicipaddress_info:
    resource_group: "{{projectname}}_{{version}}_RG_K8s"
    name: "{{projectname}}-{{version}}-publicIpAddress"
  register: publicip
  tags: k8s

- debug:
    msg: "{{publicip.publicipaddresses[0].ip_address}}"
  tags: k8s

- name: (Cluster Configuration) Deploy K8s File
  shell: | 
    cat <<EOF |  kubectl apply -f -
    apiVersion: v1
    kind: Secret
    metadata:
      name: dbsecret
      namespace: "{{namespace}}"
    type: Opaque
    data:
      DB_USER: "{{ dbuserk8s | b64encode }}"
      DB_PASSWORD: "{{ dbsecret | b64encode }}"

    ---
    # Configmap-notejam

    apiVersion: v1
    kind: ConfigMap
    data:
      DB_URL: "{{dbname}}.postgres.database.azure.com"
      DB_PORT: "5432"
      DB_NAME: "notejam"
    metadata:
      creationTimestamp: null
      labels:
        app: all
      name: global-configmap
      namespace: {{namespace}}  
    ---

    # Deployment - Notetam

    apiVersion: apps/v1
    kind: Deployment
    metadata: 
      labels: 
        app: notejam
      name: notejam-deployment
      namespace: {{namespace}}
    spec: 
      replicas: 1
      selector:
        matchLabels:
          app: notejam
      strategy: 
        type: Recreate
      template: 
        metadata: 
          labels: 
            app: notejam
        spec:
          restartPolicy: Always
          containers:
          - name: notejam
            image: "arundil/notejam:latest"
            imagePullPolicy: Always
            ports:
            - containerPort: 8000
            command: 
              - /bin/bash
              - -c
              - /notejam/init.sh
            env: 
              - name: DB_URL
                valueFrom: 
                  configMapKeyRef: 
                    key: DB_URL
                    name: global-configmap
              - name: DB_PORT
                valueFrom: 
                  configMapKeyRef: 
                    name: global-configmap
                    key: DB_PORT
              - name: DB_NAME
                valueFrom: 
                  configMapKeyRef: 
                    name: global-configmap
                    key: DB_NAME
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: dbsecret
                    key: DB_USER
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: dbsecret
                    key: DB_PASSWORD
    ---

    # Service - Notetam

    apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        app: notejam
      name: notejam
      namespace: {{namespace}}
    spec:
      ports:
      - name: "8000"
        port: 8000
        targetPort: 8000
      selector:
        app: notejam
    status:
      loadBalancer: {}

    ---
    # Deployment nginx

    apiVersion: apps/v1
    kind: Deployment
    metadata:
      namespace: {{namespace}}
      annotations:
        app: nginx
      creationTimestamp: null
      labels:
        app: nginx
      name: nginx-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: nginx
      strategy:
        type: Recreate
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: nginx
        spec:
          containers:
          - image: arundil/nginx:latest
            imagePullPolicy: Always
            name: nginx
            ports:
            - containerPort: 80
            - containerPort: 443
            resources: {}
          restartPolicy: Always
    ---

    # Service - NGINX

    apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
      name: nginx-service-lb
      namespace: {{namespace}}
    spec:
      type: LoadBalancer
      ports:
      - name: "http"
        port: 80
        targetPort: 80
      - name: https
        port: 443
        targetPort: 443
      selector:
        app: nginx
    ---
    EOF

  tags: k8s