#####################################
#   Task: 2)Install Namespaces      #
#        Role: cluster config       #
#####################################
#                                   #
#        Author:Marc Bayon          #
#####################################

- name: (Cluster Configuration) Verify the ingress namespace exits
  shell: kubectl get namespace ingress-basic
  ignore_errors: yes
  register: namespace_ingress_result
  tags: namespaces

- set_fact:
    exitsIngrns: "{{namespace_ingress_result.stdout_lines}}"
  tags: namespaces


- name: (Cluster Configuration) Verify the platform namespace exits
  shell: kubectl get namespace adasplatform
  ignore_errors: yes
  register: namespace_platf_result
  tags: namespaces

- set_fact:
    exitsPlatfns: "{{namespace_platf_result.stdout_lines}}"
  tags: namespaces

- name: (Cluster Configuration) Create ingress namespace
  shell: kubectl create namespace adasplatform
  when: exitsPlatfns|length == 0
  tags: namespaces