name: Notejam

on:
  push:
    branches:
      - 'main'

jobs:
  dockerize-notejam:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: containers/notejam-container/
          push: true
          tags: arundil/notejam:latest

    dockerize-nginx:
    steps:
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: containers/nginx-container/
          push: true
          tags: arundil/nginx:latest
