name: Notejam

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create env file
        run: |
          touch containers/notejam-container/.env
          echo DB_URL="dbnotejam.postgres.database.azure.com" >> containers/notejam-container/.env
          echo DB_PORT="5432" >> containers/notejam-container/.env
          echo DB_USER="posgres@dbnotejam" >> containers/notejam-container/.env
          echo DB_PASSWORD="${{ secrets.DB_PASSWORD }}" >> containers/notejam-container/.env
          cat containers/notejam-container/.env
        
      - name: Create priv key for https
        run: |
          touch containers/nginx-container/certs/privkey.pem
          echo "${{ secrets.PRIVKEY }}" >> containers/nginx-container/certs/privkey.pem

      - name: Build the stack
        run: docker-compose -f containers/docker-compose.yaml up -d
      - name: Test
        run: curl https://localhost
      
  # push-dockerhub:
  #   runs-on: ubuntu-latest
  #   steps:
      # -
      #   name: Checkout
      #   uses: actions/checkout@v2
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     -
  #       name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Build and push notejam
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: containers/notejam-container/
  #         push: true
  #         tags: arundil/notejam:latest

  #       name: Build and push nginx
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: containers/nginx-container/
  #         push: true
  #         tags: arundil/nginx:latest
