name: Notejam

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          DB_URL: "dbnotejam.postgres.database.azure.com"
          DB_PORT: "5432"
          DB_NAME: "notejam"
          DB_USER: "posgres@dbnotejam"
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          directory: containers/notejam-container/
          file_name: .env
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f containers/docker-compose.yaml up -d
      - name: Test
        run: curl https://localhost
      
  # push-dockerhub:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v2
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     -
  #       name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Build and push notejam
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: containers/notejam-container/
  #         push: true
  #         tags: arundil/notejam:latest

  #       name: Build and push nginx
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: containers/nginx-container/
  #         push: true
  #         tags: arundil/nginx:latest
